language: go
go_import_path: qvl.io/httpsyet
go:
  - 1.14.2
os:
  - linux
  - osx
after_success: |
  test "$TRAVIS_OS_NAME" = "linux" -a -n "$TRAVIS_TAG" \
  && curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh \
  && ./bin/goreleaser
